KEYWORDS = [
    "Art Show",
    "Aufführung",
    "Ausstellung",
    "Award Ceremony",
    "Beginn",
    "Charity",
    "Club"
    "Clubnight",
    "Concert",
    "Conference",
    "Convention",
    "Einlass",
    "Eintritt",
    "Exhibition",
    "Festival",
    "Fundraiser",
    "Gala",
    "Konferenz",
    "Konzert",
    "Kunstausstellung",
    "Launch",
    "Lecture",
    "Meeting",
    "Messe",
    "Networking",
    "Netzwerken",
    "Party",
    "Performance",
    "Präsentation",
    "Preisverleihung",
    "Presentation",
    "Seminar",
    "Spendenaktion",
    "Symposium",
    "Tagung",
    "Trade Show",
    "Treffen",
    "Veranstaltung",
    "Vortrag",
    "Webinar",
    "Wohltätigkeitsveranstaltung",
    "Workshop",
    "Event",
]
